[package]
name = "distinct-float"
version = "0.0.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
pipe-trait = "0.4.0"
serde = { version = "1.0.163", features = ["derive"], optional = true }

[dev-dependencies]
pretty_assertions = "1.3.0"

[features]
default = ["std"]
std = ["serde"]
